language: r
cache: packages
r: 
  - release
notifications:
  email: false
before_install:
  - export TZ=US/Pacific
  - sudo apt-get -qq update
  - sudo apt-get install libgmp3-dev r-cran-ggmap
# Install packages
install:
  - Rscript -e "install.packages(c('ggmap', 'methods', 'rmarkdown', 'knitr'), repos='http://cran.r-project.org')"
  - Rscript -e "library(methods); library(rmarkdown); library(knitr); rmarkdown::render('test.Rmd')"
# Run test
script:
  - make all

